[Tue, 17 Dec 2013 10:48:58] ADValidate.py[line:117] ERROR search error
[Tue, 17 Dec 2013 10:57:46] ADValidate.py[line:117] INFO {'info': '000004DC: LdapErr: DSID-0C0906E8, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v1db1', 'desc': 'Operations error'}
[Tue, 17 Dec 2013 10:57:46] ADValidate.py[line:118] ERROR 此用户不存在！
[Tue, 17 Dec 2013 10:58:18] ADValidate.py[line:117] DEBUG {'info': '000004DC: LdapErr: DSID-0C0906E8, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v1db1', 'desc': 'Operations error'}
[Tue, 17 Dec 2013 10:58:18] ADValidate.py[line:118] ERROR 此用户不存在！
[Tue, 17 Dec 2013 10:59:30] ADValidate.py[line:117] DEBUG {'info': '000004DC: LdapErr: DSID-0C0906E8, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v1db1', 'desc': 'Operations error'}
[Tue, 17 Dec 2013 11:00:41] ADValidate.py[line:117] DEBUG {'info': '000004DC: LdapErr: DSID-0C0906E8, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v1db1', 'desc': 'Operations error'}
[Tue, 17 Dec 2013 11:00:41] ADValidate.py[line:118] DEBUG <class 'ldap.OPERATIONS_ERROR'>
[Tue, 17 Dec 2013 11:00:41] ADValidate.py[line:119] ERROR 此用户不存在！
[Tue, 17 Dec 2013 11:02:28] ADValidate.py[line:118] DEBUG {'info': '000004DC: LdapErr: DSID-0C0906E8, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v1db1', 'desc': 'Operations error'}
[Tue, 17 Dec 2013 11:02:28] ADValidate.py[line:119] DEBUG <class 'ldap.OPERATIONS_ERROR'>
[Tue, 17 Dec 2013 11:02:28] ADValidate.py[line:120] ERROR 此用户不存在！
[Tue, 17 Dec 2013 11:08:11] ADValidate.py[line:117] ERROR 此用户不存在！
[Tue, 17 Dec 2013 11:16:45] ADValidate.py[line:117] ERROR 此用户不存在！
[Tue, 17 Dec 2013 11:16:45] ADValidate.py[line:86] ERROR 认证过程失败
[Tue, 17 Dec 2013 11:19:40] ADValidate.py[line:117] ERROR 此用户不存在
[Tue, 17 Dec 2013 11:19:40] ADValidate.py[line:86] ERROR administratori用户名不正确，认证过程失败
[Tue, 17 Dec 2013 11:21:11] ADValidate.py[line:70] ERROR 密码为空，认证过程失败
[Tue, 17 Dec 2013 13:12:51] ADValidate.py[line:70] ERROR 密码为空，认证过程失败
[Tue, 17 Dec 2013 13:13:40] ADValidate.py[line:117] ERROR 此用户不存在
[Tue, 17 Dec 2013 13:13:50] ADValidate.py[line:86] ERROR administratori用户名不正确，认证过程失败
[Tue, 17 Dec 2013 13:15:17] ADValidate.py[line:117] ERROR 此用户不存在
[Tue, 17 Dec 2013 13:15:17] ADValidate.py[line:86] ERROR administratori用户名不正确，认证过程失败
[Tue, 17 Dec 2013 13:15:34] ADValidate.py[line:117] ERROR 此用户不存在
[Tue, 17 Dec 2013 13:15:36] ADValidate.py[line:86] ERROR administratori用户名不正确，认证过程失败
[Tue, 17 Dec 2013 13:17:35] ADValidate.py[line:118] ERROR 此用户不存在
[Tue, 17 Dec 2013 13:17:35] ADValidate.py[line:86] ERROR administratori用户名不正确，认证过程失败
[Tue, 17 Dec 2013 13:17:54] ADValidate.py[line:119] ERROR 此用户不存在
[Tue, 17 Dec 2013 13:17:54] ADValidate.py[line:86] ERROR administratori用户名不正确，认证过程失败
[Tue, 17 Dec 2013 13:18:17] ADValidate.py[line:117] ERROR 此用户不存在
[Tue, 17 Dec 2013 13:18:17] ADValidate.py[line:86] ERROR administratori用户名不正确，认证过程失败
[Tue, 17 Dec 2013 13:19:01] ADValidate.py[line:118] ERROR 此用户不存在
[Tue, 17 Dec 2013 13:19:01] ADValidate.py[line:86] ERROR administratori用户名不正确，认证过程失败
[Tue, 17 Dec 2013 13:19:20] ADValidate.py[line:118] ERROR 此用户不存在
[Tue, 17 Dec 2013 13:19:20] ADValidate.py[line:86] ERROR administratori用户名不正确，认证过程失败
[Tue, 17 Dec 2013 13:19:30] ADValidate.py[line:118] ERROR 此用户不存在
[Tue, 17 Dec 2013 13:19:30] ADValidate.py[line:86] ERROR administratori用户名不正确，认证过程失败
[Tue, 17 Dec 2013 13:19:36] ADValidate.py[line:118] ERROR 此用户不存在
[Tue, 17 Dec 2013 13:19:36] ADValidate.py[line:86] ERROR administratori用户名不正确，认证过程失败
[Tue, 17 Dec 2013 13:20:26] ADValidate.py[line:118] ERROR 此用户不存在
[Tue, 17 Dec 2013 13:20:26] ADValidate.py[line:86] ERROR administratori用户名不正确，认证过程失败
[Tue, 17 Dec 2013 13:22:30] ADValidate.py[line:118] ERROR 此用户不存在
[Tue, 17 Dec 2013 13:22:30] ADValidate.py[line:86] ERROR administratori用户名不正确，认证过程失败
[Tue, 17 Dec 2013 13:23:38] ADValidate.py[line:117] ERROR 此用户不存在
[Tue, 17 Dec 2013 13:23:38] ADValidate.py[line:86] ERROR administratori用户名不正确，认证过程失败
[Tue, 17 Dec 2013 13:24:41] ADValidate.py[line:117] ERROR 此用户不存在
[Tue, 17 Dec 2013 13:24:41] ADValidate.py[line:86] ERROR administratori用户名不正确，认证过程失败
[Tue, 17 Dec 2013 13:25:06] ADValidate.py[line:117] ERROR 此用户不存在
[Tue, 17 Dec 2013 13:25:06] ADValidate.py[line:86] ERROR administratori用户名不正确，认证过程失败
[Tue, 17 Dec 2013 13:25:50] ADValidate.py[line:117] ERROR 此用户不存在
[Tue, 17 Dec 2013 13:25:50] ADValidate.py[line:86] ERROR administratori用户名不正确，认证过程失败
[Tue, 17 Dec 2013 13:26:11] ADValidate.py[line:117] ERROR 此用户不存在
[Tue, 17 Dec 2013 13:26:11] ADValidate.py[line:86] ERROR administratori用户名不正确，认证过程失败
[Tue, 17 Dec 2013 13:27:37] ADValidate.py[line:117] ERROR 此用户不存在
[Tue, 17 Dec 2013 13:27:37] ADValidate.py[line:86] ERROR administratori用户名不正确，认证过程失败
[Tue, 17 Dec 2013 13:28:07] ADValidate.py[line:117] ERROR 此用户不存在
[Tue, 17 Dec 2013 13:28:07] ADValidate.py[line:86] ERROR administratori用户名不正确，认证过程失败
[Tue, 17 Dec 2013 13:28:22] ADValidate.py[line:117] ERROR 此用户不存在
[Tue, 17 Dec 2013 13:28:25] ADValidate.py[line:86] ERROR administratori用户名不正确，认证过程失败
[Tue, 17 Dec 2013 13:28:57] ADValidate.py[line:117] ERROR 此用户不存在
[Tue, 17 Dec 2013 13:29:00] ADValidate.py[line:86] ERROR administratori用户名不正确，认证过程失败
[Tue, 17 Dec 2013 13:32:53] ADValidate.py[line:117] ERROR 此用户不存在
[Tue, 17 Dec 2013 13:33:38] ADValidate.py[line:119] ERROR 此用户不存在
[Tue, 17 Dec 2013 13:33:38] ADValidate.py[line:88] ERROR administratori用户名不正确，认证过程失败
[Tue, 17 Dec 2013 13:34:14] ADValidate.py[line:119] ERROR 此用户不存在
[Tue, 17 Dec 2013 13:34:14] ADValidate.py[line:88] ERROR administratori用户名不正确，认证过程失败
[Tue, 17 Dec 2013 13:58:34] ADValidate.py[line:118] ERROR 此用户不存在
[Tue, 17 Dec 2013 13:58:34] ADValidate.py[line:87] ERROR administratori用户名不正确，认证过程失败
[Tue, 17 Dec 2013 14:05:35] ADValidate.py[line:118] ERROR 此用户不存在
[Tue, 17 Dec 2013 14:05:35] ADValidate.py[line:87] ERROR administratori用户名不正确，认证过程失败
[Tue, 17 Dec 2013 14:06:29] ADValidate.py[line:118] ERROR 此用户不存在
[Tue, 17 Dec 2013 14:06:29] ADValidate.py[line:87] ERROR administratori用户名不正确，认证过程失败
[Tue, 17 Dec 2013 14:11:03] ADValidate.py[line:74] ERROR 密码为空，认证过程失败
[Tue, 17 Dec 2013 14:13:11] ADValidate.py[line:74] ERROR 密码为空，认证过程失败
[Tue, 17 Dec 2013 15:08:34] ADValidate.py[line:74] ERROR 密码为空，认证过程失败
